@startuml Etats.png
    state "Démo" as demo {

    state "Affiche bleu" as bleu
    bleu : Pour indiquer
    bleu : le mode en cours

    state "Mode démo" as Demo
    Demo : Fait varier la couleur
    Demo : automatiquement

    [*] --> bleu
    bleu --> Demo : 1 seconde
    }

    state "Intéraction" as inter {

    state "Affiche rouge" as rouge
    rouge : Pour indiquer
    rouge : le mode en cours

    state "Mémoire" as mem
    mem : Affiche la couleur
    mem : mémorisée.

    state "Choix de la couleur" as choix
    choix : Faire tourner l'ange
    choix : affiche une couleur en particulier
    choix : Suivant l'axe de rotation, on
    choix : agis soit sur X, soit sur Y
    choix : soit sur Z.

    [*] --> rouge
    rouge --> mem : 1 seconde
    mem --> choix : single tap
    choix --> mem : single tap

    }

    state "Sonore" as micro {
    state "Affiche vert" as vert
    vert : Pour indiquer
    vert : le mode en cours

    state "Pulsation" as pulse
    pulse : Fait pulser la couleur
    pulse : mémorisée.

    state "Éteinte" as off
    off : N'affiche plus aucune
    off : lumière.

    [*] --> vert
    vert --> pulse : 1 seconde
    pulse --> off : aucun son
    off -> pulse : présence de son
    }

    demo --> inter : double tap
    inter -> micro : double tap
    micro --> demo : double tap
@enduml
